/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ADD_H_RPCGEN
#define _ADD_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct numbers {
	int a;
	int b;
	char op[5];
};
typedef struct numbers numbers;

#define OpProg 0x1234567
#define ADD_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define addF 1
extern  int * addf_1(numbers *, CLIENT *);
extern  int * addf_1_svc(numbers *, struct svc_req *);
#define subF 2
extern  int * subf_1(numbers *, CLIENT *);
extern  int * subf_1_svc(numbers *, struct svc_req *);
#define mulF 3
extern  int * mulf_1(numbers *, CLIENT *);
extern  int * mulf_1_svc(numbers *, struct svc_req *);
#define divF 4
extern  int * divf_1(numbers *, CLIENT *);
extern  int * divf_1_svc(numbers *, struct svc_req *);
extern int opprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define addF 1
extern  int * addf_1();
extern  int * addf_1_svc();
#define subF 2
extern  int * subf_1();
extern  int * subf_1_svc();
#define mulF 3
extern  int * mulf_1();
extern  int * mulf_1_svc();
#define divF 4
extern  int * divf_1();
extern  int * divf_1_svc();
extern int opprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_numbers (XDR *, numbers*);

#else /* K&R C */
extern bool_t xdr_numbers ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ADD_H_RPCGEN */
